spring.application.name=api
#configuração para ler arquivo .env
spring.config.import=optional:file:.env[.properties]
spring.datasource.url = ${DB_URL}
spring.datasource.username = ${USERNAME_DB}
spring.datasource.password = ${PASSWORD_DB}